name: etbert
channels:
  - conda-forge

dependencies:
  - python=3.8.20
  - pip=24.3.1
  - setuptools
  - wheel

  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8
  - ca-certificates
  - ld_impl_linux-64
  - libffi
  - libgcc
  - libgcc-ng
  - libgomp
  - liblzma
  - liblzma-devel
  - libnsl
  - libsqlite
  - libuuid
  - libxcrypt
  - libzlib
  - ncurses
  - openssl
  - readline
  - tk
  - xz

  - pip:
      - numpy==1.24.4
      - packaging==24.2
      - pandas==2.0.3
      - pillow==10.4.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - regex==2024.11.6
      - six==1.17.0
      - tqdm==4.67.1
      - typing-extensions==4.12.2
      - tzdata==2025.1

      # ---- Three PyTorch packages ----
      - torch==1.9.0+cu111
      - torchvision==0.10.0+cu111
      - torchaudio==0.9.0

      # ---- This is REQUIRED ----
      - -f https://download.pytorch.org/whl/torch_stable.html
